services:
  vietnamese-embedding-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vietnamese-embedding-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./models_cache:/app/models_cache
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 600s
    shm_size: 2G