version: '3.8'

services:
  vietnamese-embedding-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vietnamese-embedding-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - EMBEDDING_MODEL_NAME=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - DEVICE=cpu
      - LOG_LEVEL=ERROR
      - DEFAULT_EMBEDDING_DIMENSIONS=384
      - TRANSFORMERS_CACHE=/home/app/.cache/huggingface
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - huggingface_cache:/home/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

volumes:
  huggingface_cache: