version: '3.8'

services:
  vietnamese-embedding-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vietnamese-embedding-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME:-sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2}
      - DEVICE=${DEVICE:-cpu}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}  # Changed to DEBUG
      - TRANSFORMERS_CACHE=/home/app/.cache/huggingface
      - TORCH_HOME=/home/app/.cache/torch
      # Add memory debugging
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      # Create named volumes with proper permissions
      - huggingface_cache:/home/app/.cache/huggingface
      - torch_cache:/home/app/.cache/torch
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s  # 5 minutes for model download
    deploy:
      resources:
        limits:
          memory: 6G  # Increased memory limit
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    # Add memory settings
    shm_size: 2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  huggingface_cache:
    driver: local
  torch_cache:
    driver: local